 const Hogs = [
    {'name': "Mudblood",
     'isShowing': false,
     'specialty': "Mediocre magic",
     'greased': false,
     'weight': 2.0,
     'highest medal achieved': 'bronze'
  },
    {'name': "Porkchop",
     'isShowing': false,
     'specialty': "Making friends",
     'greased': true,
     'weight': 1.6,
     'highest medal achieved': 'silver'
  },
    {'name': "Cherub",
     'isShowing': false,
     'specialty': "truffle finder",
     'greased': false,
     'weight': 0.7,
     'highest medal achieved': 'gold'
  },
    {'name': "Piggy smalls",
     'isShowing': false,
     'specialty': "Massivity",
     'greased': true,
     'weight': 5.1,
     'highest medal achieved': 'platinum'
  },
    {'name': "Trouble",
     'isShowing': false,
     'specialty': "Racing",
     'greased': true,
     'weight': 1.7,
     'highest medal achieved': 'gold'
  },
    {'name': "Sobriety",
     'isShowing': false,
     'specialty': "Expert Witness",
     'greased': false,
     'weight': 2.2,
     'highest medal achieved': 'silver'
  },
    {'name': "Rainbowdash",
     'isShowing': false,
     'specialty': "Union Busting",
     'greased': false,
     'weight': 3.7,
     'highest medal achieved': 'wood'
  },
    {'name': "TruffleShuffle",
     'isShowing': false,
     'specialty': "Finding truffles",
     'greased': true,
     'weight': 4.0,
     'highest medal achieved': 'gold'
  },
    {'name': "Bay of Pigs",
     'isShowing': false,
     'specialty': "Hamphlet Distribution",
     'greased': false,
     'weight': 2.8,
     'highest medal achieved': 'diamond'
  },
    {'name': "The Prosciutto Concern",
     'isShowing': false,
     'specialty': "truffle finder",
     'greased': false,
     'weight': 2.3,
     'highest medal achieved': 'bronze'
  },
    {'name': "Galaxy Note",
     'isShowing': false,
     'specialty': "Airport Security",
     'greased': true,
     'weight': 1.9,
     'highest medal achieved': 'diamond'
  },
    {'name': "Leggo My Eggo",
     'isShowing': false,
     'specialty': "Babysitting",
     'greased': true,
     'weight': 3.3,
     'highest medal achieved': 'platinum'
  },
    {'name': "Augustus Gloop",
     'isShowing': false,
     'specialty': "Vacuum tubes",
     'greased': true,
     'weight': 4.1,
     'highest medal achieved': 'wood'
  }
]

export default Hogs
